function createfigure(X1, YMatrix1)
%CREATEFIGURE(X1, YMatrix1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 31-May-2021 22:07:29

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Marker','diamond','LineStyle','--','Parent',axes1);
set(plot1(1),'DisplayName','Third','Color',[0 0 0]);
set(plot1(2),'DisplayName','Fifth','Color',[0 0 1]);
set(plot1(3),'DisplayName','Seventh','Color',[1 0 0]);
set(plot1(4),'DisplayName','Ninth','Color',[0 1 0]);
set(plot1(5),'DisplayName','Eleventh','Marker','v','Color',[0 0 0]);
set(plot1(6),'DisplayName','Thirteenth','Marker','v','Color',[0 0 1]);
set(plot1(7),'DisplayName','Fifteenth','Marker','v','Color',[1 0 0]);

% Create ylabel
ylabel('Total Harmonic Distortion');

% Create xlabel
xlabel('Grid Impedance');

% Create title
title('AC Choke = 1.5mH & DC choke = 1.5mH ');

box(axes1,'on');
hold(axes1,'off');
% Create legend
legend(axes1,'show');

