%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/shalakasitre/Desktop/Testsystem.xlsx
%    Worksheet: Harmonic numbers
%
% Auto-generated by MATLAB on 14-Apr-2021 17:57:53

%% Setup the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 11);

% Specify sheet and range
opts.Sheet = "Harmonic numbers";
opts.DataRange = "A1:K401";

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2", "rdharmonic", "thharmonic", "thh", "thh1", "thh2", "thh3", "thh4", "VarName10", "overallthd"];
opts.VariableTypes = ["string", "double", "double", "double", "double", "double", "double", "double", "double", "string", "double"];

% Specify variable properties
opts = setvaropts(opts, ["VarName1", "VarName10"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["VarName1", "VarName10"], "EmptyFieldRule", "auto");

% Import the data
TestsystemS4 = readtable("/Users/shalakasitre/Desktop/Testsystem.xlsx", opts, "UseExcel", false);


%% Clear temporary variables
clear opts